version: '2'
services:
  db:
    image: convox/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: vagrant
      MYSQL_DATABASE: wpt
      MYSQL_USER: vagrant
      MYSQL_PASSWORD: vagrant

  redis:
    image: convox/redis
    restart: always
    ports:
      - 6379:6379
    environment:
      LINK_PASSWORD: vagrant

  backend:
    build: .
    links:
      - db
      - redis
    ports:
      - 8080:8080
