version: '2'
services:
  db:
    image: convox/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpt
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password

  redis:
    image: convox/redis
    restart: always
    ports:
      - 6379:6379
    environment:
      LINK_PASSWORD: vagrant
      LINK_USERNAME: vagrant
      
  backend:
    build: .
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports:
      - 80:80
