version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: vagrant
      MYSQL_DATABASE: wpt
      MYSQL_USER: vagrant
      MYSQL_PASSWORD: vagrant

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    image: php:7.0
    dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /webroot/
      - /etc/nginx/sites-enabled/
      - /Users/gilleyj/Projects/docker-chef/convox-wpt/data_logs/nginx/:/var/log/nginx/

