FROM php:7.0

ENV CONVOX_DEBUG 	1
ENV CONVOX_DIR		"/Users/gilleyj/Projects/docker-chef/convox-wpt/"
ENV PROJECT_DIR		"/Users/gilleyj/Projects/wpt/"

COPY /Users/gilleyj/Projects/docker-chef/convox-wpt/nginx_conf /etc/nginx/sites-enabled/
COPY /Users/gilleyj/Projects/wpt/ /vagrant_wpt/
